Hd viz manager
Spaghetti-Code-G6/HD-Viz pull request #17
Opened 2021-05-23 08:08 UTC by Ubriacopo

Gestore principale della applicazione con metodi testati. 
Aggiornato anche l'UML

2021-05-23 09:55 UTC, danielcontro requested changes
Ho dei dubbi sul perchè HDVizManager debba essere un subject, non dovrebbe semplicemente occuparsi di gestire le istanze e lasciarle dialogare tra di loro con observer?
Per quanto riguarda i test organizzali in 
```
describe('HDVizManager', () => {
  describe('<metodo>', () => {
    it('<test case>', () => {
    })
  })
})
```
di modo da avere una suite per metodo e una per tutto il tipo, velocizzando il testing e facilitando la manutenzione

2021-05-23 09:55 UTC, danielcontro commented on server/modules/hdVizManager/HdVizManager.js
> +}
Probabilmente si può rendere più snello e leggibile con map e filter e utilizzarla semplicemente inline senza bisogno di definire una funzione a parte (si eviterebbero anche side effects così)

2021-05-23 09:55 UTC, danielcontro commented on server/modules/hdVizManager/HdVizManager.js
> +    filterGraphs.call(this, graphs)
- Manca il bind della funzione privata (nel caso venga mantenuta)
- Manca il type check nel dataset

2021-05-23 09:55 UTC, danielcontro commented on server/modules/hdVizManager/HdVizManager.js
> +    /** Make new dataset assignment. (type check?) */
Aggiungere type check (principio "fail fast")

2021-05-23 09:55 UTC, danielcontro commented on server/modules/hdVizManager/HdVizManager.js
> +    this.notify(new Event(EventType.DATA_LOADED, null, this))
Credo che debba notificare agli observer il nuovo dataset e non this

2021-05-23 09:55 UTC, danielcontro commented on server/modules/hdVizManager/HdVizManager.js
> +     *  Do we want to throw exception or simply return false and do nothing? */
Direi che sia meglio lanciare eccezioni e lasciare al chiamante gestirle ("fail fast" altrimenti)

2021-05-23 09:55 UTC, danielcontro commented on server/modules/hdVizManager/HdVizManager.js
> +    const index = _this.graphs.findIndex(graph => graph instanceof graphModel.constructor)
Non credo serva il check nel costruttore ma basti un indexOf(graphModel)

2021-05-23 09:55 UTC, danielcontro commented on server/modules/hdVizManager/HdVizManager.js
> +    return privates.get(this).current >= 0 ? privates.get(this).graphs[privates.get(this).current] : null
_this per ridurre i privates.get(this)

2021-05-23 09:55 UTC, danielcontro commented on server/modules/hdVizManager/HdVizManager.js
> +HdVizManager.prototype.removeGraph = function (graphModel){
Manca documentazione del metodo e non capisco il caso d'uso della funzione, perchè dovremmo dare esteriormente la possibilità di rimuovere un grafico?

2021-05-23 09:55 UTC, danielcontro commented on server/modules/hdVizManager/HdVizManager.js
> +HdVizManager.prototype.selectGraph = function (selected) {
Manca documentazione del metodo (tipo del parametro)

2021-05-23 17:06 UTC, Ubriacopo commented on server/modules/hdVizManager/HdVizManager.js
> +HdVizManager.prototype.removeGraph = function (graphModel){
Era nel caso volessimo la possibilità, ora l'ho cancellato

2021-05-23 17:06 UTC, Ubriacopo commented on server/modules/hdVizManager/HdVizManager.js
> +    return privates.get(this).current >= 0 ? privates.get(this).graphs[privates.get(this).current] : null
Okay fatto

2021-05-23 17:10 UTC, Ubriacopo commented on server/modules/hdVizManager/HdVizManager.js
> +    const index = _this.graphs.findIndex(graph => graph instanceof graphModel.constructor)
A noi serve però sapere se abbiamo due istanze dello stesso tipo, indexOf prende una variabile e fa match sul valore

2021-05-23 17:12 UTC, Ubriacopo commented on server/modules/hdVizManager/HdVizManager.js
> +    this.notify(new Event(EventType.DATA_LOADED, null, this))
Giusto, passo anche il vecchio dataset in oldstate

2021-05-25 16:30 UTC, danielcontro commented on server/modules/hdVizManager/__mocks__/EventType.js
> +    SUBJECT_DESTROYED: Symbol('SUBSJECT_DESTROYED'),
```suggestion
    SUBJECT_DESTROYED: Symbol('SUBJECT_DESTROYED'),
```

2021-05-25 16:36 UTC, danielcontro approved these changes

2021-05-25 16:36 UTC, merged